[package]
name = "code-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
syntect = "4.6.0"
glob = "0.3.0"
tqdm-rs = "0.1.0"